[Geithain]
title = "ME-Geithain Blog"
url = "https://www.me-geithain.de/de/blog.html"
entrySelector = ".main-content-holder"
titleSelector = "h3"
linkSelector = "a"

[RME]
title = "RME Treiber"
url = "https://rme-audio.de/home.html"
entrySelector = ".download-item1"
titleSelector = "a"
linkSelector = "a"
dateSelector = "strong"
dateFormat = "LL/dd/uuuu"
